#!/bin/bash

#Make sure correct file hierarchies exist
if [ ! -d raycheck2.out/image ]; then
    echo "Please make sure raycheck2.out exists!"
    exit -1
fi

# Copy directory tree structure to new folders
rsync -a -f"+ */" -f"- *" raycheck2.out/image/ raycheck2.out/diffs
rsync -a -f"+ */" -f"- *" raycheck2.out/image/ raycheck2.out/montage

# Process
for file in $(find raycheck2.out/image/ -type f); do
    FULL_FNAME="$(realpath --relative-to="raycheck2.out/image/" $file)"
    FNAME=${FULL_FNAME%.*}

    echo "Processing $FNAME"

    IMGNAME=raycheck2.out/image/"$FNAME".png
    REFNAME=raycheck2.out/refcache/"$FNAME".std.png
    OUTNAME=raycheck2.out/diffs/"$FNAME".diff.png
    DIFNAME=raycheck2.out/montage/"$FNAME".mont.png

    compare "$IMGNAME" "$REFNAME" "$OUTNAME"
    montage "$IMGNAME" "$REFNAME" "$OUTNAME" -tile 3x1 -geometry +0+0 "$DIFNAME"
done

trap "echo Quitting...; exit -2" SIGINT SIGTERM
